comment:
  layout: header, changes, diff, sunburst
coverage:
  ignore:
    - tandoori_.+/tests.*
  status:
    patch:
      default:
        target: 95%
    project:
      default:
        target: auto
